### ISSUE TITLE
CPU占用高

### ISSUE THREAD

**Issue by juqkai** [LiRenTech/project-graph#10]
应该是为了渲染图形，对每一帧都做了渲染，从而导致了CPU持续占用

**Comment by zty012** [comment]
如何复现（

**Comment by Littlefean** [comment]
CPU持续占用多少，CPU等性能配置信息可以了解一下吗？

**Comment by juqkai** [comment]
![image](https://github.com/user-attachments/assets/bd0eb8b2-5049-4c80-abaf-8021d65c80b3)

什么也没有操作的情况下
大概CPU平均占用3.8%

**Comment by juqkai** [comment]
![image](https://github.com/user-attachments/assets/356d9e68-6421-47c3-9eb6-4a48acbf9ae2)

**Comment by zty012** [comment]
![image](https://github.com/user-attachments/assets/5a446c5d-39d0-45f2-bb54-517f78cdd49e)

linux可复现

**Comment by Littlefean** [comment]
突然想到一个方案：既然只有在操作的时候是有动画的绘制，大部分不操作的情况下就相当于一张静态的图片。

那么只要一检测到操作，就让接下来的300帧迭代内更新动画渲染，其余的时候不更新

**Comment by Rutubet** [comment]
优化这个的办法是在一个集中的地方，掌控所有数据的变化，根据这些数据的变化，选择比较好的方案进行重绘。例如，仅仅当数据发生变化时进行重绘，但是同时也限制重绘的频率不高于某个设定值。要做到这些事情，需要涉及到大量代码的重构，目前我正在考虑这个事情。

**Comment by Littlefean** [comment]
用tauri写的v2版本好像cpu占用很低了。

如果哪一天测试发现很占性能再打开这个issue

**Comment by TomIsFat** [comment]
### 占用CPU的进程
下图这个进程不知道为什么一直占用CPU
![Image](https://github.com/user-attachments/assets/9999bf88-ad19-4469-bb72-2fdd919fbc20)
软件就放在后台什么都没做，占用有点高

### 与其他软件的后台占用对比
![Image](https://github.com/user-attachments/assets/3c6af28c-50aa-4ae8-ad97-5be02399417f)
后台的占用算是里面比较高的

### 简单的测试
软件就放在后台什么都没做
主界面时（一个节点和多个节点性能占用没有区别），这个进程的占用大约是1%
进入设置界面时，这个进程的占用大约是0.3%
说明主界面的占用很高

### 测试条件
下图是性能设置
![Image](https://github.com/user-attachments/assets/d3e28a8e-41ee-449d-bf07-c9a87dc3cf77)

V1.4.24
