### ISSUE TITLE
选中后的工具按钮菜单容易误触

### ISSUE THREAD

**Issue by mgk95** [LiRenTech/project-graph#112]
![图片1231](https://github.com/user-attachments/assets/f1a86c03-a2e5-4dee-88ff-092edefc6f8c)
如果可以的话，希望能把工具按钮，挪到上方，老是误触删除。

**Comment by Littlefean** [comment]
项目已在2024年10月2日从pyqt框架重写成tauri框架，目前功能的实现还停留在接近第一期视频中的样子。
目前打算tauri版本中
![Q91P IXB SG}YDX)7OC}M2A](https://github.com/user-attachments/assets/342a3006-ab1d-40bc-bbd7-a35ba8c19cc9)
将工具栏改成右侧数列常驻页面显示

**Comment by Littlefean** [comment]
新版本已实现
