### ISSUE TITLE
撤销历史记录限制大小

### ISSUE THREAD

**Issue by juqkai** [LiRenTech/project-graph#12]
也就是传统的ctrl+z 撤销操作，以及重做

**Comment by Littlefean** [comment]
撤销功能做好了，Ctrl+Z撤销、Ctrl+Shift+Z取消撤销，重做在第一个菜单栏里。

但目前历史记录是无限大小的，操作步骤上千步骤之后可能会卡了，因为每帧都在遍历渲染一个双向链表显示在调试信息里，可能打算加一个限制历史记录大小。

**Comment by Littlefean** [comment]
已完成
