### ISSUE TITLE
Macos 无法打开

### ISSUE THREAD

**Issue by TheAnsIs42** [LiRenTech/project-graph#131]
版本0.4.0
Macos 15.0.1 (24A348)
打开时显示已损坏
<img width="237" alt="截屏2024-10-30 16 49 41" src="https://github.com/user-attachments/assets/1117f6bc-7fb2-4636-a6da-99d2331d58f4">

**Comment by zty012** [comment]
https://github.com/zzzgydi/clash-verge/issues/369

**Comment by zty012** [comment]
在终端中运行

```sh
sudo xattr -r -d com.apple.quarantine /Applications/Project\ Graph.app
```
