### ISSUE TITLE
左右滚动逻辑问题

### ISSUE THREAD

**Issue by TheAnsIs42** [LiRenTech/project-graph#154]
使用快捷键（shift+滚轮）左右滚动时，滚轮只要偏离原来位置，画布就会一直滚动，只有滚轮回到开始的位置才停止。松开shift也不会停止。不符合滚轮转动多少滚动多少的逻辑。

**Comment by Littlefean** [comment]
感谢反馈，左右滚动逻辑还没有完善好，出现这个问题的原因是：我的鼠标有一个侧边滚轮，我想把它利用起来就尝试增加水平滚动的功能，但还没有做好。我猜测大部分人的鼠标应该没有侧边滚轮所以这个代码就被保留在软件里了。

但有点困惑的是在测试时我发现shift+滚轮触发的还是缩放的功能，没有触发侧向滚动。我的环境是win11。不知道是否和环境有关系。

**Comment by Littlefean** [comment]
好像确实是系统差异，我注意到您曾经在 #131 提到过关于macos的问题，可能macos系统中的shift+滚轮会等效于windows系统中的横向滚动，而windows系统中的shift+滚轮不会触发横向滚动。
后续会完善横向滚动功能。

**Comment by TheAnsIs42** [comment]
抱歉忘了说，这个issue是在linux下发现的，我最一开始也是使用侧边滚轮发现的，可能是使用快捷键软件的原因shift+滚轮也能复现。

**Comment by Littlefean** [comment]
今天上午的NightlyBuild修复了这个问题，不过没有丝滑的过度效果
