### ISSUE TITLE
✨ 节点碰撞挤压增加开关设置项

### ISSUE THREAD

**Issue by lovedreamms** [LiRenTech/project-graph#184]
### 我已阅读并同意以下条款

- [x] 我已尝试使用 [Nightly Build](https://github.com/LiRenTech/project-graph/releases/nightly)，并且没有我想要的功能
- [x] 我已浏览 [Issues](https://github.com/LiRenTech/project-graph/issues) 并且没有找到类似的功能请求

### 功能描述

BiliBili的视频有效的展示了碰撞带来的绘图感觉

**Comment by Littlefean** [comment]
1.1.0版本已支持，但是是强制开启，还没加开关设置

**Comment by Littlefean** [comment]
已增加开关，在设置>性能里开启和关闭。
由于目前这个碰撞很容易出bug，所以先默认是关闭状态
