### ISSUE TITLE
🐛 Mac 版本打开就报错了

### ISSUE THREAD

**Issue by orangelckc** [LiRenTech/project-graph#196]
### 发生了什么？

![Image](https://github.com/user-attachments/assets/79860e7c-ffd6-4d9f-a805-9482bc2c216c)
打开软件CPU占用猛升，应该是在检测鼠标位置吧

### 系统版本

macOS

**Comment by Littlefean** [comment]
感觉可能和readme里面“src-tauri/tauri.conf.json”的修改有关系，目前配置文件还是windows的

**Comment by zty012** [comment]
> 感觉可能和readme里面“src-tauri/tauri.conf.json”的修改有关系，目前配置文件还是windows的

感觉和webview版本有关

**Comment by zty012** [comment]
![Image](https://github.com/user-attachments/assets/2cddd5ac-3c6f-41bd-881e-5396883ad108)
这个问题很奇怪，webkit17支持roundRect,但是获取不到这个方法

**Comment by 522247020** [comment]
不报错，但是打开点击无响应，会莫名其妙的退出。

**Comment by allinu** [comment]
不报错，但是打开后怎么操作都没有反应

**Comment by allinu** [comment]
Macbook air m1 15.2 (24C101) 打开不报错，无响应
