### ISSUE TITLE
🐛 在窗口截图时，截图完毕后会一直移动画布

### ISSUE THREAD

**Issue by dongrentianyu** [LiRenTech/project-graph#197]
### 发生了什么？

打开软件，随便写上一个节点，随便写上什么内容。然后用windows自带的，截图快捷键截图区域。就会出现位置一直下移的问题。而且无法停止。感觉像是受到了快捷键的影响。

### 系统版本

Windows

**Comment by Littlefean** [comment]
建议在设置-控制 中关闭wsad移动画布

**Comment by ovechou** [comment]
你好

**Comment by Littlefean** [comment]
出现一直下移可能是快捷键字母是w或s。没检测到按键松开导致的。如果快捷键是ctrl+alt+a，可能会出现一直左或右移动的bug。
这个bug一直挺难修。很多游戏里甚至也会出现滚屏bug

**Comment by Littlefean** [comment]
![Image](https://github.com/user-attachments/assets/45c6817f-156c-43e3-ad9f-774dd14850e3)

**Comment by dongrentianyu** [comment]
好的。但一般使用中还是会开启wasd，因为开启之后移动会更方便一点。

我也只是截图给朋友看的时候才发现这个bug的。
