### ISSUE TITLE
🐛 按住 Alt 右键拖动节点时未拖动到其他节点而释放发生错误

### ISSUE THREAD

**Issue by sheep-realms** [LiRenTech/project-graph#200]
#### 复现方法
1. 按住 Alt 键；
2. 右键按住任意节点；
3. （也可以在此时按住 Alt 键）；
4. 拖拽至空白区域释放鼠标

### 系统版本

Windows

### 附件

![Image](https://github.com/user-attachments/assets/6ffbe833-46d8-4a2b-9947-c06e8cb042ed)

**Comment by Littlefean** [comment]
已修复，明天NightlyBuild自动更新发布开发版。
