### ISSUE TITLE
🐛 工具栏的弹出菜单布局在跨越不同缩放率的显示器时出现问题

### ISSUE THREAD

**Issue by sheep-realms** [LiRenTech/project-graph#201]
### 发生了什么？

![Image](https://github.com/user-attachments/assets/50bd6e8f-bf3d-46c4-bd02-ecf83a4cce35)

如图所示，节点对齐工具和颜色工具的菜单布局在跨越不同缩放率的显示器时出现问题。

作为参考，以下是我的显示器信息：

**显示器1：**
分辨率：3200*1800
缩放：200%

**显示器2：**
分辨率：1366*768
缩放：100%

### 系统版本

Windows

**Comment by zty012** [comment]
这不是 Project Graph 的 Bug，请在 [tauri-apps/wry](https://github.com/tauri-apps/wry)、[Chromium Issues](https://issues.chromium.org)、[MicrosoftEdge/WebView2Feedback](https://github.com/MicrosoftEdge/WebView2Feedback) 中创建 Issue
