### ISSUE TITLE
打包MacOS版本

### ISSUE THREAD

**Issue by panAtGitHub** [LiRenTech/project-graph#25]
您好，我不懂软件开发，但在 B 站上看到这个软件，感觉挺有趣，咨询下，这个软件可以在 mac 上进行运行么？

**Comment by zty012** [comment]
可以从源代码运行，或者自行打包

**Comment by zty012** [comment]
https://github.com/LiRenTech/project-graph-qt/blob/master/docs/CONTRIBUTING.md

**Comment by panAtGitHub** [comment]
谢谢您的回复，但小白确实看不懂打包教程——毕竟不是学软件开发的。
哈哈哈，等下次有mac 安装包时，再来试用试用吧。

**Comment by zty012** [comment]
MacOS  打包已经可用，更多信息请关注 #113
