### ISSUE TITLE
增加功能：两节点间拉双向线后，双向线可将两线和端点手动分开，并且每条线可分别添加备注

### ISSUE THREAD

**Issue by RayLam2022** [LiRenTech/project-graph#41]

**Comment by Littlefean** [comment]
可能要详细讨论一下这个如何将两个重叠的线“手动分开”，如何手动

**Comment by clinlx** [comment]
我猜他是想画这种循环图：

![image](https://github.com/user-attachments/assets/90d10d00-a2e3-4055-bf2d-75955465362b)

但是在目前的软件架构下不太好弄。因为曲线是自动生成的。。。只和起点终点有关。。。
而且目前的双向线其实是“一条类型是双向的线”
除非增加软件复杂性，让用户自己决定线条路径（听着就好麻烦，还要考虑交互问题），或者用另一个透明的节点假装这是备注：
![image](https://github.com/user-attachments/assets/0504e636-0567-4f2a-85d3-93e4e2d95b1f)

> 可能要详细讨论一下这个如何将两个重叠的线“手动分开”，如何手动

**Comment by Littlefean** [comment]
其实目前的架构下，双向线是两条单项的线重叠在一起了。
我的想法是自动检测，如果有两个节点互相连了线
A -> B
B -> A
那么自动生成算法的线条就会自动错开，A -> B的线条会朝着一个方向错开一定位置，B -> A 的线条会朝着另一个方向错开一定位置，这样就能分别选中并编辑线上的文字了

**Comment by Littlefean** [comment]
![$LLU%59A{GE5JF55M 33D81](https://github.com/user-attachments/assets/e854e9fa-8eed-4a8c-9b94-81e1319adf2f)
![%}4Y$4LT@QVD`COQZ1HTM)K](https://github.com/user-attachments/assets/7e709112-a612-48c8-8371-cc19ee89e8fb)

已实现

**Comment by Littlefean** [comment]
tauri新版本待实现此功能

**Comment by Littlefean** [comment]
tauri版本已实现，并且还可以用 `反引号+左键双击`来创建“质点”来连接，实现效果
![image](https://github.com/user-attachments/assets/c29af032-07af-4329-bd5d-f2e20c253a2a)
