### ISSUE TITLE
完善复制节点功能

### ISSUE THREAD

**Issue by 123hi123** [LiRenTech/project-graph#44]
呃，目前的想法就是嗯左鍵去圈選一個區域的節點，然後可以一鍵復制
然後貼上的地方，可能就是在這個鼠標停留的地方

**Comment by Littlefean** [comment]
这个可以做，但需要一些事件，目前您可以先暂时这样来解决急需：将一小块部分保存成文件然后不停的将它拖拽到窗口里来实现复制的效果

**Comment by Littlefean** [comment]
已添加功能，框选住一些节点，然后按Alt键，同时左键拖拽复制即可。
如有关于复制功能的bug或改进，可提新issue。

**Comment by 123hi123** [comment]
謝謝作者實現得那麼快
不過還是好奇說為什麼不使用一般常用的快捷鍵control C control V來實踐這個功能感覺在使用上會更加的直觀嗎？

**Comment by Littlefean** [comment]
- [ ] 增加ctrl c 、ctrl v 复制粘贴功能
- [ ] 实现连续Alt键拖拽，而不是每次Alt拖拽都要从原位置拖拽，每次Alt拖拽自动把选中状态移动到新复制出来的地方上
- [ ] 完善渲染，把Alt拖拽过程中的链接也绘制上

**Comment by Littlefean** [comment]
这些功能需要等待Ctrl+Z和Ctrl+shift+Z功能实现之后再实现。 #12

**Comment by Littlefean** [comment]
新版本已实现

**Comment by 123hi123** [comment]
太強了 這下不得不更新了
