### ISSUE TITLE
新版本自定义的颜色选择功能

### ISSUE THREAD

**Issue by clinlx** [LiRenTech/project-graph#57]
如题，今天UI似乎进行了一次小幅度的更新，但是新版本的颜色选择面板实际上不起作用。双击右键打开颜色面板，选择了颜色然后点击确定，并不能更改颜色。更新之前是正常的。

**Comment by Littlefean** [comment]
其实之前的颜色更改一直处于测试阶段，还没有打算正式加入，因为自己调色感觉很容易调出来各种极端的不协调颜色，并且和不同的主题风格（科技蓝、黑客帝国、马卡龙色系）不太搭配。

目前是打算出一些有特殊含义的节点属性值，比如“重要”，“已完成”，“进行中”等等，然后在不同的主题风格中设置这些颜色。

比如在黑客帝国风格中，“重要”节点就是亮绿色，“已完成”节点就是暗绿色。但是在其他风格里就又是另外一套颜色体系。

这个其实还有待思考和设计

**Comment by Littlefean** [comment]
自定义颜色好几天前就加了，在release中，有一个“最后的PyQt版本”，目前的想法是节点支持自定义更改颜色，同时也提供几个特殊的颜色用来快速更改颜色。

但昨天项目已经用tauri框架重写了，PyQt版本不再维护。目前tauri还在开发中。

**Comment by Littlefean** [comment]
tauri版本已实现修改颜色，但还欠缺完全自定义的颜色修改
![image](https://github.com/user-attachments/assets/ce0b9434-7104-44e0-8296-ed446e8093c5)
