### ISSUE TITLE
支持Ctrl和Shift选择

### ISSUE THREAD

**Issue by clinlx** [LiRenTech/project-graph#58]
在选择一大堆目标以后，Windows系统在大多数时候可以使用Ctrl键来取消选择一些目标，或者额外增加选择一些目标。

如若加入类似的功能，能完善多选功能。让其更为泛用。

至于使用哪个快捷键其实无所谓。选一个不会和将来规划的快捷键冲突的键位即可。

**Comment by Littlefean** [comment]
已在新版本tauri实现，pyqt版本已经不再更新
