### ISSUE TITLE
实现对齐功能

### ISSUE THREAD

**Issue by clinlx** [LiRenTech/project-graph#66]
希望能使用快捷键来使得节点对齐到某些特殊格点。（当前的格子不适合用于对齐，显得太大了）

比如：按住Alt键后拖动，会使得移动节点时自动向着最近的格点吸附

现版本如果需要画平齐的多个节点是很麻烦的。就连文档样例里面的“框选多重连线”演示也是参差不齐不在同一水平面上的。

即使是使用↑↓←→选择+Tab来向右创建水平节点，结果也不是完全平行的，而是新的节点会大致水平，但略微偏向右上。

另外，目前这个“网格显示”的功能不明所以。因为既不能自动对齐，如果你想用来当作参照物手动对齐的话，也只有中心区域有，一旦离开中心区域这个网络不会自动拓展。

下面是其他成熟软件中“利用网格进行对齐”，以及“网格进行拓展”，的演示：（全部来自流程图设计网站draw.io）

[1]此网站默认为吸附状态
![对齐网格](https://github.com/user-attachments/assets/d15ac0f5-396d-4e4f-9c3b-b0c8e20144ae)

[2]此网站拖动时按住Alt会取消吸附
![无对齐](https://github.com/user-attachments/assets/95be947a-507e-4e4d-8e2d-e443ba0945bb)

[3]此网站当节点离开格子画布时，会对格子画布进行拓展
![网格拓展](https://github.com/user-attachments/assets/d4ec3490-ac22-4997-885d-2d93689f92ab)

**Comment by Littlefean** [comment]
### 目前的网格用处确实太小了：
它只是最开始在测试的时候绘制一下，只看个大概距离概念（一个格子是100px - 世界坐标），以便在画面空荡荡的情况下知道自己是否缩放镜头了。以及知道坐标轴原点在哪里（在拖拽其他的导图json文件到窗口画布内的时候会有用），并没有想到用网格来设计对齐功能。

### 对齐功能的原计划
之前打算框选一些节点之后，像Adobe系列的软件一样，能够左对齐、顶对齐、水平居中对齐、右侧对齐等等。弹出的工具栏会出现这些对齐图标。（姑且叫框选对齐）

### 如果急需水平对齐功能：
新功能需要做一段时间，如果目前急需水平对齐，有一个生草的办法：可以新建一个节点，写一个长长的名字，把节点撑大成一个巨长的长方形，然后拖拽它和其他节点碰撞，利用挤压特性把一些节点水平对齐。

### 对网格的想法：
draw.io应该是有解决打印需求的，纸张是固定大小的，所以会出现移出边界时会自动拓展一块区域的特性。
project-graph 打算后面增加导出图片的功能，根据节点分布位置情况找到所有节点的最小外接矩形并留一定的边距，确定导出图片的大小。
实际上网格应该全空间显示，而不是只显示坐标原点一小块区域。（这个应该也好解决，只绘制视野框里的矩形即可）

### 和原方案对比
如果做网格对齐，可能需要和框选对齐权衡一下，是做框选对齐还是做网格对齐，还是两个都要？
网格对齐似乎更适合非常严格精准的画图，每个节点的坐标位置都对齐在坐标轴上。
框选对齐可能更加快捷方便，只将需要的部分节点排列整齐

**Comment by clinlx** [comment]
框选对齐的方案听着也不错。简洁快速。是做在删除按钮边上，之前占位的工具栏上吗？

**Comment by Littlefean** [comment]
> 框选对齐的方案听着也不错。简洁快速。是做在删除按钮边上，之前占位的工具栏上吗？

对的，
![image](https://github.com/user-attachments/assets/eb486516-f832-4082-876d-7775ef417ce2)
类似这种图标

**Comment by clinlx** [comment]
网格全空间显示，其实就是每当摄像机发送改变的时候，用纯数学方式计算一下视野内应该有哪些网格线就行了。

根据当前摄像机范围的数量级，做一个显示相应比例的网格线就行了。如果缩放过小的网格线就不显示，避免同框出现太多线条。

比如：如果摄像机当前能看到80px宽的地方，，就显示每10px一条的细线和每100px一条的粗线；如果摄像机当前能看到900px宽的地方，就显示每100px一条的细线和每1000px一条的粗线。

**Comment by Littlefean** [comment]
网格全空间显示已增加到issue： #68

**Comment by Littlefean** [comment]
目前对齐功能已经实现在工具栏了，至于网格功能也许不是那么刚需了，这个就先关闭了，如果后面出现需要网格的情况可以再开新isuee。

**Comment by Littlefean** [comment]
新版本tauri待实现此功能

**Comment by Littlefean** [comment]
已实现
