### ISSUE TITLE
加个版本号吧

### ISSUE THREAD

**Issue by clinlx** [LiRenTech/project-graph#69]
软件里面看不到当前的版本。

在下载页面也只有一个下载链接，也没有Github的Release记录，也没有更新公告，不知道云端构建的最新版本到底是多少，到底是否和我硬盘上的版本相同。

也就不知道是否要重新下一遍，就算重新下载了，重新运行了，我也确定不了我到底是“根本没有更新”，还是“我暂时没发现更新的内容在哪”。除非我自己先不管三七二十一下载后，再去算MD5进行比较。

**Comment by zty012** [comment]
计划：在关于对话框显示当前的commit hash
