### ISSUE TITLE
測試了新版本 然後希望之後更新能發個release甚麼也好 或者拉個群之類的 內文是新版本體驗心得

### ISSUE THREAD

**Issue by 123hi123** [LiRenTech/project-graph#70]
先說 真的很喜歡這個工具

新版本體驗下來修復了打開最近編輯功能
ui的一點變動
最好的一個改動是最底下提示有甚麼功能的改動變得清出(雙級左鍵調整顏色的功能也可以提示下)

缺點
變卡了 我有一個文件大約10000KB 舊版開啟滑動沒什麼問題 新版的話滑動視窗 刪除節點都變卡了

**Comment by zty012** [comment]
卡顿的问题请看 #10，如果你有QQ的话可以加入群聊972047940，我正在考虑创建Telegram或Discord群组

**Comment by Littlefean** [comment]
> 卡顿的问题请看 #10，如果你有QQ的话可以加入群聊972047940，我正在考虑创建Telegram或Discord群组

这个QQ群是b站观众学习交流群，说不定哪天就满了

**Comment by Littlefean** [comment]
![Discord](https://img.shields.io/discord/1281228823844880437?logo=discord&cacheSeconds=0)

**Comment by Littlefean** [comment]
这个卡顿的问题主要是绘制渲染，我有一次更新把字体抖动解决了，但代价就是渲染卡顿了。

我打算再恢复这个情况。

**Comment by 123hi123** [comment]
感謝 QQ 加了 期待這個項目未來的發展
