### ISSUE TITLE
添加临时涂鸦轨迹特效，增强演示教学场景

### ISSUE THREAD

**Issue by Littlefean** [LiRenTech/project-graph#81]
类似于GoodNotes的临时红色激光笔轨迹，像个特效一样闪一下消失，用于视频录制介绍中实用

**Comment by zty012** [comment]
数据结构:
```python
list[list[NumberVector]]
```
`list[NumberVector]`代表一条线
![image](https://github.com/user-attachments/assets/f4fa7091-f1c1-469f-a080-a6e434d9d382)
`NumberVector`代表一个顶点，最多`2**31`个顶点，如果超过了就把偶数索引值的元素删除
