### ISSUE TITLE
建议增加一个节点均分的功能

### ISSUE THREAD

**Issue by lxj5820** [LiRenTech/project-graph#99]
当选中多个节点时，让他们以左右上下最远的两个节点为范围，以垂直或水平的方向，均匀分布

**Comment by Littlefean** [comment]
垂直和水平均匀分布漏做了，打算做在工具栏里的。

**Comment by Littlefean** [comment]
已在新版本实现
![image](https://github.com/user-attachments/assets/ec809453-8b38-4ecc-9770-559411d188a9)
